name: VoteParty
main: me.clip.voteparty.plugin.VotePartyPlugin

version: '@version@'
website: 'https://helpch.at/discord'
authors: ['Glare', 'Clip', 'Sxtanna']

depend:
  - 'PlaceholderAPI'
softdepend:
  - 'Votifier'

api-version: '1.13'
description: 'Reward players with random commands being executed for them when the server gets x amount of votes'


permissions:
  voteparty.command.admin:
    description: 'Ability to use all admin commands'
    default: op
  voteparty.command.claim:
    description: 'Ability to claim offline vote rewards'
    default: true